#!/bin/sh

#Default values
export ARTIFACTORY_HOME=/artifactory
export ARTIFACTORY_USER=root
export JAVA_HOME=/usr/lib/jvm/java-8-oracle-amd64

export TOMCAT_HOME=/artifactory/tomcat
export ARTIFACTORY_PID=$ARTIFACTORY_HOME/run/artifactory.pid

export JAVA_OPTIONS="-server -Xms512m -Xmx2g -Xss256k -XX:PermSize=128m -XX:MaxPermSize=256m -XX:+UseG1GC"
